Repository intel/AiCSD, pull requests merged in 2023-12, with the labels that each got.

#59 feat: upgrade mqtt export configuration from toml to yaml
  edgex-res/mqtt-export-configuration.toml
  edgex-res/mqtt-export-configuration.yaml
Labels: EdgeX 3.1

#63 feat: Use App SDK 3.1.
  as-file-receiver-oem/config/configuration.go
  as-file-receiver-oem/controller/controller.go
  as-file-receiver-oem/controller/controller_test.go
  as-file-receiver-oem/functions/functions.go
  as-file-receiver-oem/functions/functions_test.go
  as-file-receiver-oem/main.go
  as-file-sender-gateway/config/configuration.go
  as-file-sender-gateway/controller/controller.go
  as-file-sender-gateway/controller/controller_test.go
  as-file-sender-gateway/main.go
  as-pipeline-sim/config/configuration.go
  as-pipeline-sim/controller/controller.go
  as-pipeline-sim/functions/functions.go
  as-pipeline-sim/main.go
  as-pipeline-val/config/configuration.go
  as-pipeline-val/controller/controller.go
  as-pipeline-val/controller/controller_test.go
  as-pipeline-val/main.go
  as-task-launcher/config/config.go
  as-task-launcher/controller/controller.go
  as-task-launcher/controller/controller_test.go
  as-task-launcher/main.go
  as-task-launcher/persist/redis.go
  as-task-launcher/persist/redis_test.go
  go.mod
  go.sum
  ms-data-organizer/config/config.go
  ms-data-organizer/controller/controller.go
  ms-data-organizer/controller/controller_test.go
  ms-data-organizer/main.go
  ms-file-receiver-gateway/config/config.go
  ms-file-receiver-gateway/controller/filehandler.go
  ms-file-receiver-gateway/controller/filehandler_test.go
  ms-file-receiver-gateway/main.go
  ms-file-sender-oem/config/config.go
  ms-file-sender-oem/controller/filehandler.go
  ms-file-sender-oem/controller/filehandler_test.go
  ms-file-sender-oem/main.go
  ms-file-watcher/config/config.go
  ms-file-watcher/controller/filehandler.go
  ms-file-watcher/main.go
  ms-job-repository/config/config.go
  ms-job-repository/controller/controller.go
  ms-job-repository/controller/controller_test.go
  ms-job-repository/main.go
  ms-job-repository/persist/redis.go
  ms-job-repository/persist/redis_test.go
  pkg/helpers/helpers.go
  pkg/wait/wait.go
Labels: dependencies, EdgeX 3.1

#65 feat: Complete migration of as-file-receiver-oem to EdgeX 3.1
  as-file-receiver-oem/Dockerfile
  as-file-receiver-oem/res/configuration.toml
  as-file-receiver-oem/res/configuration.yaml
Labels: dependencies
