Repository intel/AiCSD, pull requests merged in 2024-06, with the labels that each got.

#93 Update reviewdog.yaml
  .github/workflows/reviewdog.yaml
Labels: dependabot

#94 feat:(go mod): updated spiffe which updates go-jose to v4
  go.mod
  go.sum
Labels: dependabot

#99 fix: resolving issues with codeQL
  ms-file-receiver-gateway/controller/filehandler.go
  ms-file-sender-oem/controller/filehandler.go
Labels: dependabot

#96 fix: fix path expression
  geti-pipeline/example_code/demo.py
Labels: dependabot, python

#100 fix: fixing codeQL path issue
  ms-file-sender-oem/controller/filehandler.go
Labels: dependabot

#101 doc: update system-setup.md
  docs_src/getting-started/system-setup.md
Labels: documentation
