Repository intel/AiCSD, pull requests merged in 2025-01, with the labels that each got.

#122 fix: address golang dependabot patches
  go.mod
  go.sum
Labels: dependabot

#124 fix: update ca-certificates pinned version in Dockerfiles
  as-file-receiver-oem/Dockerfile
  as-file-sender-gateway/Dockerfile
  as-pipeline-sim/Dockerfile
  as-pipeline-val/Dockerfile
  as-task-launcher/Dockerfile
  ms-data-organizer/Dockerfile
  ms-file-receiver-gateway/Dockerfile
  ms-file-sender-oem/Dockerfile
  ms-file-watcher/Dockerfile
  ms-job-repository/Dockerfile
Labels: dependencies

#126 Catalog docs
  docs_src/catalog/Get-Started-Guide.md
  docs_src/catalog/images/DisplayAllJobs.jpg
  docs_src/catalog/images/FillFormTask.png
  docs_src/catalog/images/docker-ps-sim.png
  docs_src/catalog/images/install-successful.png
  docs_src/catalog/images/webui-add-task.png
  docs_src/index.md
Labels: documentation
